//! Chime's signaling frames: the protobuf messages, how they go on the
//! wire, and the ones this client sends.
//!
//! The messages come from `SignalingProtocol.proto` in AWS's
//! amazon-chime-sdk-js (Apache-2.0, vendored beside this file with its
//! NOTICE), compiled ahead of time into `chime/signaling_protocol.rs` so
//! the build needs no `protoc`. Every WebSocket message is one byte, 0x05
//! ("RTC"), then an `SdkSignalFrame` (`DefaultSignalingClient`'s
//! `prependWithFrameTypeRTC`).

use prost::Message as _;

/// The generated protocol. Its names are protobuf's, not ours.
#[allow(
    missing_docs,
    clippy::all,
    clippy::pedantic,
    rust_2018_idioms,
    reason = "generated by prost-build from Chime's .proto"
)]
pub mod proto {
    include!("chime/signaling_protocol.rs");

    /// Shows who the credentials are for, never the password.
    impl std::fmt::Debug for SdkTurnCredentials {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.debug_struct("SdkTurnCredentials")
                .field(
                    "username",
                    &self.username.as_ref().map(|_| crate::redact::REDACTED),
                )
                .field(
                    "password",
                    &self.password.as_ref().map(|_| crate::redact::REDACTED),
                )
                .field("ttl", &self.ttl)
                .field("uris", &self.uris)
                .finish()
        }
    }

    /// Never shows the join token.
    impl std::fmt::Debug for SdkMeetingSessionCredentials {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            f.debug_struct("SdkMeetingSessionCredentials")
                .field("attendee_id", &self.attendee_id)
                .field("external_user_id", &self.external_user_id)
                .field(
                    "join_token",
                    &self.join_token.as_ref().map(|_| crate::redact::REDACTED),
                )
                .finish()
        }
    }
}

pub use proto::SdkSignalFrame as Frame;
pub use proto::sdk_signal_frame::Type as FrameType;

/// The byte before every frame: Chime's "RTC" frame type.
pub const RTC: u8 = 0x05;
/// The query the JS SDK puts on the signaling URL
/// (`SignalingClientConnectionRequest.url`).
pub const URL_QUERY: &str = "X-Chime-Control-Protocol-Version=3&X-Amzn-Chime-Send-Close-On-Error=1";
/// The WebSocket subprotocol that comes before the join token
/// (`SignalingClientConnectionRequest.protocols`).
pub const SUBPROTOCOL: &str = "_aws_wt_session";
/// The SDK this client says it is, as HuddleFM does
/// (`src/native-media/signaling.ts`, `join`).
pub const SDK_NAME: &str = "amazon-chime-sdk-js";
/// The SDK version the vendored protocol comes from.
pub const SDK_VERSION: &str = "3.31.0";

/// The signaling URL with the query Chime expects.
pub fn signaling_url(base: &str) -> String {
    let joiner = if base.contains('?') { '&' } else { '?' };
    format!("{base}{joiner}{URL_QUERY}")
}

/// Why bytes off the socket are not a frame.
#[derive(Clone, Debug, PartialEq, Eq, thiserror::Error)]
pub enum FrameError {
    #[error("an empty message")]
    Empty,
    #[error("frame type byte {0:#04x}, not RTC")]
    Kind(u8),
    #[error("protobuf: {0}")]
    Decode(String),
}

/// The bytes for one WebSocket message.
pub fn encode(frame: &Frame) -> Vec<u8> {
    let mut bytes = Vec::with_capacity(frame.encoded_len() + 1);
    bytes.push(RTC);
    // Encoding into a Vec cannot run out of room.
    let _ = frame.encode(&mut bytes);
    bytes
}

/// Reads one WebSocket message. The JS SDK also takes type 0x02, with a
/// warning; so does this.
pub fn decode(bytes: &[u8]) -> Result<Frame, FrameError> {
    let (&kind, body) = bytes.split_first().ok_or(FrameError::Empty)?;
    if kind != RTC && kind != 0x02 {
        return Err(FrameError::Kind(kind));
    }
    Frame::decode(body).map_err(|e| FrameError::Decode(e.to_string()))
}

/// A frame of `kind` stamped `now_ms`, with nothing in it yet.
pub fn frame(kind: FrameType, now_ms: u64) -> Frame {
    Frame {
        timestamp_ms: now_ms,
        r#type: kind as i32,
        ..Frame::default()
    }
}

/// Who this client says it is in its JOIN.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ClientDetails {
    pub app_name: String,
    pub app_version: String,
}

impl Default for ClientDetails {
    fn default() -> Self {
        Self {
            app_name: "NoSlacking".into(),
            app_version: env!("CARGO_PKG_VERSION").into(),
        }
    }
}

/// The JOIN: protocol 2, with attendee presence (`HAS_STREAM_UPDATE`),
/// and plain SDP, as HuddleFM sends it. `audio_session_id` stays the same
/// for one attendee's whole stay.
pub fn join(details: &ClientDetails, audio_session_id: u32, now_ms: u64) -> Frame {
    let mut frame = frame(FrameType::Join, now_ms);
    frame.join = Some(proto::SdkJoinFrame {
        protocol_version: Some(2),
        flags: Some(proto::SdkJoinFlags::HasStreamUpdate as u32),
        client_details: Some(proto::SdkClientDetails {
            app_name: Some(details.app_name.clone()),
            app_version: Some(details.app_version.clone()),
            device_model: Some(std::env::consts::OS.into()),
            device_make: Some(std::env::consts::ARCH.into()),
            platform_name: Some("NoSlacking".into()),
            platform_version: Some(details.app_version.clone()),
            client_source: Some(SDK_NAME.into()),
            chime_sdk_version: Some(SDK_VERSION.into()),
            os_name: Some(std::env::consts::OS.into()),
            ..Default::default()
        }),
        audio_session_id: Some(u64::from(audio_session_id)),
        // No zlib here; Chime then sends plain SDP.
        wants_compressed_sdp: Some(false),
        ..Default::default()
    });
    frame
}

/// What a SUBSCRIBE says.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Subscribe {
    /// The SDP offer, already in the form Chime takes.
    pub sdp_offer: String,
    /// `MediaPlacement.AudioHostUrl`.
    pub audio_host: String,
    pub attendee_id: String,
    /// Whether to say the microphone is muted. A listener is.
    pub muted: bool,
}

/// The SUBSCRIBE that asks to receive audio, like the JS SDK's
/// `DefaultSignalingClient.subscribe` with an audio host and no video: one
/// send stream for the audio m-line, receive-only service. HuddleFM also
/// lists one receive stream id of 0 for its inactive video m-line.
pub fn subscribe(sub: &Subscribe, now_ms: u64) -> Frame {
    let mut frame = frame(FrameType::Subscribe, now_ms);
    frame.sub = Some(proto::SdkSubscribeFrame {
        duplex: Some(proto::SdkStreamServiceType::Rx as i32),
        send_streams: vec![proto::SdkStreamDescriptor {
            stream_id: Some(1),
            framerate: Some(15),
            max_bitrate_kbps: Some(600),
            track_label: Some("AmazonChimeExpressAudio".into()),
            group_id: Some(1),
            avg_bitrate_bps: Some(400_000),
            attendee_id: Some(sub.attendee_id.clone()),
            media_type: Some(proto::SdkStreamMediaType::Audio as i32),
            ..Default::default()
        }],
        receive_stream_ids: vec![0],
        sdp_offer: Some(sub.sdp_offer.clone()),
        audio_host: Some(sub.audio_host.clone()),
        audio_checkin: Some(false),
        audio_muted: Some(sub.muted),
        ..Default::default()
    });
    frame
}

/// The LEAVE that ends this attendee's stay; Chime answers LEAVE_ACK.
pub fn leave(now_ms: u64) -> Frame {
    let mut frame = frame(FrameType::Leave, now_ms);
    frame.leave = Some(proto::SdkLeaveFrame {});
    frame
}

/// A ping (to keep the socket's path alive) or the pong that answers one.
pub fn ping_pong(kind: proto::SdkPingPongType, ping_id: u32, now_ms: u64) -> Frame {
    let mut frame = frame(FrameType::PingPong, now_ms);
    frame.ping_pong = Some(proto::SdkPingPongFrame {
        r#type: kind as i32,
        ping_id,
    });
    frame
}

/// The frame's type by name, or its number when this protocol does not
/// know it (newer servers send types the vendored proto lacks).
pub fn type_name(frame: &Frame) -> String {
    match FrameType::try_from(frame.r#type) {
        Ok(kind) => kind.as_str_name().to_owned(),
        Err(_) => format!("type {}", frame.r#type),
    }
}

/// One line about a frame for the log: its type and what a protocol
/// mismatch needs to see, never a credential, an SDP's ICE password or
/// a fingerprint.
pub fn describe(frame: &Frame) -> String {
    let mut line = type_name(frame);
    let mut add = |text: String| {
        line.push(' ');
        line.push_str(&text);
    };
    if let Some(error) = &frame.error {
        add(format!(
            "error={} {:?}",
            error.status.unwrap_or_default(),
            error.description.as_deref().unwrap_or_default()
        ));
    }
    if let Some(ack) = &frame.joinack {
        match &ack.turn_credentials {
            Some(turn) => add(format!(
                "turn_uris=[{}] ttl={}",
                turn.uris.join(", "),
                turn.ttl.unwrap_or_default()
            )),
            None => add("no_turn_credentials".into()),
        }
        if let Some(limit) = ack.video_subscription_limit {
            add(format!("video_limit={limit}"));
        }
        if let Some(compressed) = ack.wants_compressed_sdp {
            add(format!("wants_compressed_sdp={compressed}"));
        }
    }
    if let Some(index) = &frame.index {
        add(format!(
            "participants={} sources={} at_capacity={}",
            index.num_participants.unwrap_or_default(),
            index.sources.len(),
            index.at_capacity.unwrap_or_default()
        ));
    }
    if let Some(ack) = &frame.suback {
        add(format!(
            "duplex={} answer={} allocations={} tracks={}",
            ack.duplex.unwrap_or_default(),
            ack.sdp_answer
                .as_ref()
                .map_or_else(|| "none".to_owned(), |sdp| format!("{} bytes", sdp.len())),
            ack.allocations.len(),
            ack.tracks.len()
        ));
        if ack
            .compressed_sdp_answer
            .as_ref()
            .is_some_and(|c| !c.is_empty())
        {
            add("compressed_answer".into());
        }
    }
    if let Some(sub) = &frame.sub {
        add(format!(
            "duplex={} send_streams={} receive_ids={:?} offer={} audio_host={} muted={}",
            sub.duplex.unwrap_or_default(),
            sub.send_streams.len(),
            sub.receive_stream_ids,
            sub.sdp_offer.as_ref().map_or(0, String::len),
            sub.audio_host.as_deref().unwrap_or_default(),
            sub.audio_muted.unwrap_or_default()
        ));
    }
    if let Some(status) = &frame.audio_status {
        add(format!(
            "status={}",
            status.audio_status.unwrap_or_default()
        ));
    }
    if let Some(info) = &frame.audio_stream_id_info {
        add(format!("streams={}", info.streams.len()));
    }
    if let Some(metadata) = &frame.audio_metadata {
        let speaking = metadata
            .attendee_states
            .iter()
            .filter(|s| s.volume.unwrap_or_default() > 0)
            .count();
        add(format!(
            "states={} speaking={speaking}",
            metadata.attendee_states.len()
        ));
    }
    if let Some(ping) = &frame.ping_pong {
        add(format!("kind={} id={}", ping.r#type, ping.ping_id));
    }
    if let Some(bitrates) = &frame.bitrates {
        add(format!("bitrates={}", bitrates.bitrates.len()));
    }
    if let Some(note) = &frame.notification {
        add(format!(
            "level={} {:?}",
            note.level.unwrap_or_default(),
            note.message.as_deref().unwrap_or_default()
        ));
    }
    line
}

/// What an AUDIO_STATUS code means, as the JS SDK's
/// `MeetingSessionStatus.fromAudioStatus` reads it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AudioStatus {
    Ok,
    /// The same attendee joined from another device (301).
    JoinedFromAnotherDevice,
    /// Chime ended the audio (302).
    Disconnected,
    /// The join token was refused (403).
    AuthenticationRejected,
    /// The meeting is full (409).
    AtCapacity,
    /// The meeting ended (410).
    MeetingEnded,
    /// This attendee was removed (411).
    AttendeeRemoved,
    /// A server error (500, 503): the SDK reconnects after one.
    ServerError(u32),
    /// Anything else outside 2xx: the SDK takes it as disconnected.
    Other(u32),
}

impl AudioStatus {
    /// Reads a code.
    pub fn of(code: u32) -> Self {
        match code {
            301 => Self::JoinedFromAnotherDevice,
            302 => Self::Disconnected,
            403 => Self::AuthenticationRejected,
            409 => Self::AtCapacity,
            410 => Self::MeetingEnded,
            411 => Self::AttendeeRemoved,
            500 | 503 => Self::ServerError(code),
            200..=299 => Self::Ok,
            _ => Self::Other(code),
        }
    }

    /// Whether the session is over for good: reconnecting would not help.
    pub fn is_final(self) -> bool {
        !matches!(self, Self::Ok | Self::ServerError(_))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn round_trip(frame: &Frame) -> Frame {
        let bytes = encode(frame);
        assert_eq!(bytes[0], RTC);
        decode(&bytes).expect("decodes")
    }

    #[test]
    fn frames_survive_the_wire() {
        let join = join(&ClientDetails::default(), 1234, 1_700_000_000_000);
        assert_eq!(round_trip(&join), join);
        let sub = subscribe(
            &Subscribe {
                sdp_offer: "v=0\r\n".into(),
                audio_host: "h.example:3478".into(),
                attendee_id: "A1".into(),
                muted: true,
            },
            5,
        );
        let back = round_trip(&sub);
        assert_eq!(back, sub);
        let body = back.sub.expect("a subscribe");
        assert_eq!(body.duplex, Some(proto::SdkStreamServiceType::Rx as i32));
        assert_eq!(body.send_streams[0].attendee_id.as_deref(), Some("A1"));
        assert_eq!(body.audio_muted, Some(true));
        assert_eq!(round_trip(&leave(7)), leave(7));
        let pong = ping_pong(proto::SdkPingPongType::Pong, 9, 8);
        assert_eq!(round_trip(&pong), pong);
    }

    #[test]
    fn the_join_says_what_huddlefm_says() {
        let frame = join(&ClientDetails::default(), 42, 1);
        assert_eq!(frame.r#type, FrameType::Join as i32);
        let join = frame.join.expect("a join");
        assert_eq!(join.protocol_version, Some(2));
        assert_eq!(join.flags, Some(2));
        assert_eq!(join.audio_session_id, Some(42));
        assert_eq!(join.wants_compressed_sdp, Some(false));
        let details = join.client_details.expect("details");
        assert_eq!(
            details.client_source.as_deref(),
            Some("amazon-chime-sdk-js")
        );
        assert_eq!(details.chime_sdk_version.as_deref(), Some("3.31.0"));
    }

    #[test]
    fn a_frame_from_the_js_sdk_decodes() {
        // JOIN_ACK as protobufjs encodes it: timestamp 1, type 2, joinack
        // { turn_credentials { username "u", password "p", ttl 300,
        // uris ["turn:1.2.3.4:3478?transport=udp"] } }.
        let uri = b"turn:1.2.3.4:3478?transport=udp";
        let mut turn = vec![
            0x0a,
            1,
            b'u',
            0x12,
            1,
            b'p',
            0x18,
            0xac,
            0x02,
            0x22,
            uri.len() as u8,
        ];
        turn.extend_from_slice(uri);
        let mut ack = vec![0x0a, turn.len() as u8];
        ack.extend_from_slice(&turn);
        let mut bytes = vec![RTC, 0x08, 0x01, 0x10, 0x02, 0x2a, ack.len() as u8];
        bytes.extend_from_slice(&ack);
        let frame = decode(&bytes).expect("decodes");
        assert_eq!(type_name(&frame), "JOIN_ACK");
        let turn = frame
            .joinack
            .and_then(|a| a.turn_credentials)
            .expect("turn credentials");
        assert_eq!(turn.ttl, Some(300));
        assert_eq!(turn.uris, vec!["turn:1.2.3.4:3478?transport=udp"]);
        assert!(!format!("{turn:?}").contains("\"p\""));
    }

    #[test]
    fn unknown_frame_types_still_decode() {
        // Type 99 is in no vendored enum; prost keeps the number.
        let frame = decode(&[RTC, 0x08, 0x01, 0x10, 99]).expect("decodes");
        assert_eq!(type_name(&frame), "type 99");
        assert_eq!(describe(&frame), "type 99");
    }

    #[test]
    fn garbage_is_not_a_frame() {
        assert_eq!(decode(&[]), Err(FrameError::Empty));
        assert_eq!(decode(&[0x07, 0x08]), Err(FrameError::Kind(0x07)));
        assert!(matches!(
            decode(&[RTC, 0xff, 0xff]),
            Err(FrameError::Decode(_))
        ));
    }

    #[test]
    fn descriptions_leave_secrets_out() {
        let mut ack = frame(FrameType::JoinAck, 1);
        ack.joinack = Some(proto::SdkJoinAckFrame {
            turn_credentials: Some(proto::SdkTurnCredentials {
                username: Some("1700000000:attendee".into()),
                password: Some("s3cret-password".into()),
                ttl: Some(300),
                uris: vec!["turns:t.example:443?transport=tcp".into()],
            }),
            ..Default::default()
        });
        let line = describe(&ack);
        assert_eq!(
            line,
            "JOIN_ACK turn_uris=[turns:t.example:443?transport=tcp] ttl=300"
        );
        let printed = format!("{ack:?}");
        assert!(!printed.contains("s3cret-password"), "{printed}");
        assert!(!printed.contains("1700000000:attendee"), "{printed}");
    }

    #[test]
    fn audio_statuses_read_like_the_sdk() {
        assert_eq!(AudioStatus::of(200), AudioStatus::Ok);
        assert_eq!(AudioStatus::of(410), AudioStatus::MeetingEnded);
        assert!(AudioStatus::of(410).is_final());
        assert!(AudioStatus::of(301).is_final());
        assert!(!AudioStatus::of(503).is_final());
        assert_eq!(AudioStatus::of(418), AudioStatus::Other(418));
    }

    #[test]
    fn the_signaling_url_gets_the_sdk_query() {
        assert_eq!(
            signaling_url("wss://s.example/control/M1"),
            "wss://s.example/control/M1?X-Chime-Control-Protocol-Version=3&X-Amzn-Chime-Send-Close-On-Error=1"
        );
        assert!(signaling_url("wss://s.example/c?a=1").contains("?a=1&X-Chime"));
    }
}
