// Generated from SignalingProtocol.proto (amazon-chime-sdk-js v3.31.0,
// commit dea69d268c623ab2006169d3899981fea766fa8a, Apache-2.0; see NOTICE
// and LICENSE-APACHE beside this file) by tools/chime-protogen, which
// uses prost-build with protox, so no protoc is needed. Do not edit;
// regenerate from the repository root with:
//
//   cargo run --manifest-path tools/chime-protogen/Cargo.toml -- \
//       src/huddle_audio/chime/SignalingProtocol.proto <out dir>
//
// and copy <out dir>/_.rs over this file below these lines.
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkSignalFrame {
    #[prost(uint64, required, tag = "1")]
    pub timestamp_ms: u64,
    #[prost(enumeration = "sdk_signal_frame::Type", required, tag = "2")]
    pub r#type: i32,
    #[prost(message, optional, tag = "3")]
    pub error: ::core::option::Option<SdkErrorFrame>,
    #[prost(message, optional, tag = "4")]
    pub join: ::core::option::Option<SdkJoinFrame>,
    #[prost(message, optional, tag = "5")]
    pub joinack: ::core::option::Option<SdkJoinAckFrame>,
    #[prost(message, optional, tag = "6")]
    pub sub: ::core::option::Option<SdkSubscribeFrame>,
    #[prost(message, optional, tag = "7")]
    pub suback: ::core::option::Option<SdkSubscribeAckFrame>,
    #[prost(message, optional, tag = "8")]
    pub index: ::core::option::Option<SdkIndexFrame>,
    #[prost(message, optional, tag = "10")]
    pub pause: ::core::option::Option<SdkPauseResumeFrame>,
    #[prost(message, optional, tag = "11")]
    pub leave: ::core::option::Option<SdkLeaveFrame>,
    #[prost(message, optional, tag = "12")]
    pub leave_ack: ::core::option::Option<SdkLeaveAckFrame>,
    #[prost(message, optional, tag = "14")]
    pub bitrates: ::core::option::Option<SdkBitrateFrame>,
    #[prost(message, optional, tag = "17")]
    pub audio_control: ::core::option::Option<SdkAudioControlFrame>,
    #[prost(message, optional, tag = "18")]
    pub audio_metadata: ::core::option::Option<SdkAudioMetadataFrame>,
    #[prost(message, optional, tag = "19")]
    pub audio_stream_id_info: ::core::option::Option<SdkAudioStreamIdInfoFrame>,
    #[prost(message, optional, tag = "20")]
    pub ping_pong: ::core::option::Option<SdkPingPongFrame>,
    #[prost(message, optional, tag = "21")]
    pub audio_status: ::core::option::Option<SdkAudioStatusFrame>,
    #[prost(message, optional, tag = "22")]
    pub client_metric: ::core::option::Option<SdkClientMetricFrame>,
    #[prost(message, optional, tag = "23")]
    pub data_message: ::core::option::Option<SdkDataMessageFrame>,
    #[prost(message, optional, tag = "25")]
    pub remote_video_update: ::core::option::Option<SdkRemoteVideoUpdateFrame>,
    #[prost(message, optional, tag = "26")]
    pub primary_meeting_join: ::core::option::Option<SdkPrimaryMeetingJoinFrame>,
    #[prost(message, optional, tag = "27")]
    pub primary_meeting_join_ack: ::core::option::Option<SdkPrimaryMeetingJoinAckFrame>,
    #[prost(message, optional, tag = "28")]
    pub primary_meeting_leave: ::core::option::Option<SdkPrimaryMeetingLeaveFrame>,
    #[prost(message, optional, tag = "35")]
    pub notification: ::core::option::Option<SdkNotificationFrame>,
    #[prost(message, optional, tag = "44")]
    pub meeting_session_timing: ::core::option::Option<SdkMeetingSessionTimingFrame>,
}
/// Nested message and enum types in `SdkSignalFrame`.
pub mod sdk_signal_frame {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        Join = 1,
        JoinAck = 2,
        Subscribe = 3,
        SubscribeAck = 4,
        Index = 5,
        Pause = 7,
        Resume = 8,
        Leave = 9,
        LeaveAck = 10,
        Bitrates = 13,
        AudioControl = 16,
        AudioMetadata = 17,
        AudioStreamIdInfo = 18,
        PingPong = 19,
        AudioStatus = 20,
        ClientMetric = 21,
        DataMessage = 22,
        RemoteVideoUpdate = 24,
        PrimaryMeetingJoin = 25,
        PrimaryMeetingJoinAck = 26,
        PrimaryMeetingLeave = 27,
        Notification = 34,
        MeetingSessionTiming = 43,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Join => "JOIN",
                Self::JoinAck => "JOIN_ACK",
                Self::Subscribe => "SUBSCRIBE",
                Self::SubscribeAck => "SUBSCRIBE_ACK",
                Self::Index => "INDEX",
                Self::Pause => "PAUSE",
                Self::Resume => "RESUME",
                Self::Leave => "LEAVE",
                Self::LeaveAck => "LEAVE_ACK",
                Self::Bitrates => "BITRATES",
                Self::AudioControl => "AUDIO_CONTROL",
                Self::AudioMetadata => "AUDIO_METADATA",
                Self::AudioStreamIdInfo => "AUDIO_STREAM_ID_INFO",
                Self::PingPong => "PING_PONG",
                Self::AudioStatus => "AUDIO_STATUS",
                Self::ClientMetric => "CLIENT_METRIC",
                Self::DataMessage => "DATA_MESSAGE",
                Self::RemoteVideoUpdate => "REMOTE_VIDEO_UPDATE",
                Self::PrimaryMeetingJoin => "PRIMARY_MEETING_JOIN",
                Self::PrimaryMeetingJoinAck => "PRIMARY_MEETING_JOIN_ACK",
                Self::PrimaryMeetingLeave => "PRIMARY_MEETING_LEAVE",
                Self::Notification => "NOTIFICATION",
                Self::MeetingSessionTiming => "MEETING_SESSION_TIMING",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "JOIN" => Some(Self::Join),
                "JOIN_ACK" => Some(Self::JoinAck),
                "SUBSCRIBE" => Some(Self::Subscribe),
                "SUBSCRIBE_ACK" => Some(Self::SubscribeAck),
                "INDEX" => Some(Self::Index),
                "PAUSE" => Some(Self::Pause),
                "RESUME" => Some(Self::Resume),
                "LEAVE" => Some(Self::Leave),
                "LEAVE_ACK" => Some(Self::LeaveAck),
                "BITRATES" => Some(Self::Bitrates),
                "AUDIO_CONTROL" => Some(Self::AudioControl),
                "AUDIO_METADATA" => Some(Self::AudioMetadata),
                "AUDIO_STREAM_ID_INFO" => Some(Self::AudioStreamIdInfo),
                "PING_PONG" => Some(Self::PingPong),
                "AUDIO_STATUS" => Some(Self::AudioStatus),
                "CLIENT_METRIC" => Some(Self::ClientMetric),
                "DATA_MESSAGE" => Some(Self::DataMessage),
                "REMOTE_VIDEO_UPDATE" => Some(Self::RemoteVideoUpdate),
                "PRIMARY_MEETING_JOIN" => Some(Self::PrimaryMeetingJoin),
                "PRIMARY_MEETING_JOIN_ACK" => Some(Self::PrimaryMeetingJoinAck),
                "PRIMARY_MEETING_LEAVE" => Some(Self::PrimaryMeetingLeave),
                "NOTIFICATION" => Some(Self::Notification),
                "MEETING_SESSION_TIMING" => Some(Self::MeetingSessionTiming),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkErrorFrame {
    #[prost(uint32, optional, tag = "1")]
    pub status: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "2")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkClientDetails {
    #[prost(string, optional, tag = "1")]
    pub app_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub app_version: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub device_model: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub device_make: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub platform_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub platform_version: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub client_source: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "8")]
    pub chime_sdk_version: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "9")]
    pub client_utc_offset: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "10")]
    pub os_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "11")]
    pub os_version: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkJoinFrame {
    #[prost(uint32, optional, tag = "1", default = "2")]
    pub protocol_version: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub max_num_of_videos: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub flags: ::core::option::Option<u32>,
    #[prost(message, optional, tag = "4")]
    pub client_details: ::core::option::Option<SdkClientDetails>,
    #[prost(uint64, optional, tag = "6")]
    pub audio_session_id: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "7")]
    pub wants_compressed_sdp: ::core::option::Option<bool>,
    #[prost(enumeration = "SdkServerSideNetworkAdaption", optional, tag = "10")]
    pub server_side_network_adaption: ::core::option::Option<i32>,
    #[prost(
        enumeration = "SdkServerSideNetworkAdaption",
        repeated,
        packed = "false",
        tag = "11"
    )]
    pub supported_server_side_network_adaptions: ::prost::alloc::vec::Vec<i32>,
    #[prost(bool, optional, tag = "12")]
    pub wants_all_temporal_layers_in_index: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "13")]
    pub disable_periodic_keyframe_request_on_content_sender: ::core::option::Option<
        bool,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkJoinAckFrame {
    #[prost(message, optional, tag = "1")]
    pub turn_credentials: ::core::option::Option<SdkTurnCredentials>,
    #[prost(uint32, optional, tag = "2")]
    pub video_subscription_limit: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "3")]
    pub wants_compressed_sdp: ::core::option::Option<bool>,
    #[prost(enumeration = "SdkServerSideNetworkAdaption", optional, tag = "4")]
    pub default_server_side_network_adaption: ::core::option::Option<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkLeaveFrame {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkLeaveAckFrame {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkSubscribeFrame {
    #[prost(enumeration = "SdkStreamServiceType", optional, tag = "1", default = "Rx")]
    pub duplex: ::core::option::Option<i32>,
    #[prost(message, repeated, tag = "2")]
    pub send_streams: ::prost::alloc::vec::Vec<SdkStreamDescriptor>,
    #[prost(uint32, repeated, packed = "false", tag = "3")]
    pub receive_stream_ids: ::prost::alloc::vec::Vec<u32>,
    #[prost(string, optional, tag = "4")]
    pub sdp_offer: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub audio_host: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "6")]
    pub audio_checkin: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "7")]
    pub audio_muted: ::core::option::Option<bool>,
    #[prost(bytes = "vec", optional, tag = "8")]
    pub compressed_sdp_offer: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, repeated, tag = "9")]
    pub video_subscription_configuration: ::prost::alloc::vec::Vec<
        SdkVideoSubscriptionConfiguration,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkSubscribeAckFrame {
    #[prost(enumeration = "SdkStreamServiceType", optional, tag = "1")]
    pub duplex: ::core::option::Option<i32>,
    #[prost(message, repeated, tag = "2")]
    pub allocations: ::prost::alloc::vec::Vec<SdkStreamAllocation>,
    #[prost(string, optional, tag = "3")]
    pub sdp_answer: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "4")]
    pub tracks: ::prost::alloc::vec::Vec<SdkTrackMapping>,
    #[prost(bytes = "vec", optional, tag = "5")]
    pub compressed_sdp_answer: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkIndexFrame {
    #[prost(bool, optional, tag = "1")]
    pub at_capacity: ::core::option::Option<bool>,
    #[prost(message, repeated, tag = "2")]
    pub sources: ::prost::alloc::vec::Vec<SdkStreamDescriptor>,
    #[prost(uint32, repeated, packed = "false", tag = "3")]
    pub paused_at_source_ids: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, optional, tag = "4")]
    pub num_participants: ::core::option::Option<u32>,
    #[prost(
        enumeration = "SdkVideoCodecCapability",
        repeated,
        packed = "false",
        tag = "5"
    )]
    pub supported_receive_codec_intersection: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkPauseResumeFrame {
    #[prost(uint32, repeated, packed = "false", tag = "1")]
    pub stream_ids: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, repeated, packed = "false", tag = "2")]
    pub group_ids: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkBitrateFrame {
    #[prost(message, repeated, tag = "1")]
    pub bitrates: ::prost::alloc::vec::Vec<SdkBitrate>,
    #[prost(uint32, optional, tag = "2")]
    pub server_available_outgoing_bitrate: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkStreamDescriptor {
    #[prost(uint32, optional, tag = "1")]
    pub stream_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub framerate: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub max_bitrate_kbps: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "4")]
    pub track_label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "6")]
    pub group_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "7")]
    pub avg_bitrate_bps: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "8")]
    pub attendee_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "SdkStreamMediaType", optional, tag = "9")]
    pub media_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "10")]
    pub external_user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "11")]
    pub width: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "12")]
    pub height: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkStreamAllocation {
    #[prost(string, optional, tag = "1")]
    pub track_label: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "2")]
    pub stream_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "3")]
    pub group_id: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkTrackMapping {
    #[prost(uint32, optional, tag = "1")]
    pub stream_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub ssrc: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "3")]
    pub track_label: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkBitrate {
    #[prost(uint32, optional, tag = "1")]
    pub source_stream_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub avg_bitrate_bps: ::core::option::Option<u32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkAudioControlFrame {
    #[prost(bool, optional, tag = "1")]
    pub muted: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkAudioMetadataFrame {
    #[prost(message, repeated, tag = "1")]
    pub attendee_states: ::prost::alloc::vec::Vec<SdkAudioAttendeeState>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkAudioAttendeeState {
    #[prost(uint32, optional, tag = "1")]
    pub audio_stream_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "2")]
    pub volume: ::core::option::Option<u32>,
    #[prost(bool, optional, tag = "3")]
    pub muted: ::core::option::Option<bool>,
    #[prost(uint32, optional, tag = "4")]
    pub signal_strength: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkAudioStreamIdInfoFrame {
    #[prost(message, repeated, tag = "1")]
    pub streams: ::prost::alloc::vec::Vec<SdkAudioStreamIdInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkAudioStreamIdInfo {
    #[prost(uint32, optional, tag = "1")]
    pub audio_stream_id: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "2")]
    pub attendee_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "3")]
    pub muted: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "4")]
    pub external_user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "5")]
    pub dropped: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkPingPongFrame {
    #[prost(enumeration = "SdkPingPongType", required, tag = "1")]
    pub r#type: i32,
    #[prost(uint32, required, tag = "2")]
    pub ping_id: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkAudioStatusFrame {
    #[prost(uint32, optional, tag = "1")]
    pub audio_status: ::core::option::Option<u32>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SdkMetric {
    #[prost(enumeration = "sdk_metric::Type", optional, tag = "1")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(double, optional, tag = "2")]
    pub value: ::core::option::Option<f64>,
}
/// Nested message and enum types in `SdkMetric`.
pub mod sdk_metric {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        VideoActualEncoderBitrate = 1,
        VideoAvailableSendBandwidth = 2,
        VideoRetransmitBitrate = 3,
        VideoAvailableReceiveBandwidth = 4,
        VideoTargetEncoderBitrate = 5,
        VideoBucketDelayMs = 6,
        StunRttMs = 7,
        SocketDiscardedPps = 8,
        RtcMicJitterMs = 9,
        RtcMicPps = 10,
        RtcMicFractionPacketLostPercent = 11,
        RtcMicBitrate = 12,
        RtcMicRttMs = 13,
        RtcSpkPps = 14,
        RtcSpkFractionPacketLostPercent = 15,
        RtcSpkJitterMs = 16,
        RtcSpkFractionDecoderLossPercent = 17,
        RtcSpkBitrate = 18,
        RtcSpkCurrentDelayMs = 19,
        RtcSpkJitterBufferMs = 20,
        VideoSentRttMs = 21,
        VideoEncodeUsagePercent = 22,
        VideoNacksReceived = 23,
        VideoPlisReceived = 24,
        VideoEncodeMs = 25,
        VideoInputFps = 26,
        VideoEncodeFps = 27,
        VideoSentFps = 28,
        VideoFirsReceived = 29,
        VideoSentPps = 30,
        VideoSentFractionPacketLostPercent = 31,
        VideoSentBitrate = 32,
        VideoDroppedFps = 33,
        VideoTargetDelayMs = 34,
        VideoDecodeMs = 35,
        VideoOutputFps = 36,
        VideoReceivedPps = 37,
        VideoReceivedFractionPacketLostPercent = 38,
        VideoRenderDelayMs = 39,
        VideoReceivedFps = 40,
        VideoDecodeFps = 41,
        VideoNacksSent = 42,
        VideoFirsSent = 43,
        VideoReceivedBitrate = 44,
        VideoCurrentDelayMs = 45,
        VideoJitterBufferMs = 46,
        VideoDiscardedPps = 47,
        VideoPlisSent = 48,
        VideoReceivedJitterMs = 49,
        VideoLocalRenderFps = 52,
        VideoRemoteRenderFps = 56,
        VideoInputHeight = 60,
        VideoEncodeHeight = 64,
        VideoSentQpSum = 66,
        VideoDecodeHeight = 69,
        VideoReceivedQpSum = 72,
        VideoEncodeWidth = 86,
        VideoDecodeWidth = 87,
        VideoEncoderIsHardware = 88,
        VideoDecoderIsHardware = 89,
        VideoFreezeCount = 90,
        VideoFreezeDuration = 91,
        VideoPauseCount = 92,
        VideoPauseDuration = 93,
        VideoQualityReason = 94,
        VideoProcessingTime = 95,
        RtcSpkAudioLevel = 96,
        RtcMicAudioLevel = 97,
        RtcSpkTotalLost = 98,
        RtcSpkTotalExpected = 99,
        RtcSpkTotalRecoveredRed = 100,
        RtcSpkTotalRecoveredFec = 101,
        VideoQualityLimitationDurationCpu = 102,
        VideoCodecDegradationHighEncodeCpu = 103,
        VideoCodecDegradationEncodeFailure = 104,
        VideoRenderHeight = 105,
        VideoRenderWidth = 106,
        VideoInputWidth = 107,
        VideoSentJitterMs = 108,
        AudioSentTransformPps = 109,
        AudioReceivedTransformPps = 110,
        VideoSentTransformPps = 111,
        VideoReceivedTransformPps = 112,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::VideoActualEncoderBitrate => "VIDEO_ACTUAL_ENCODER_BITRATE",
                Self::VideoAvailableSendBandwidth => "VIDEO_AVAILABLE_SEND_BANDWIDTH",
                Self::VideoRetransmitBitrate => "VIDEO_RETRANSMIT_BITRATE",
                Self::VideoAvailableReceiveBandwidth => {
                    "VIDEO_AVAILABLE_RECEIVE_BANDWIDTH"
                }
                Self::VideoTargetEncoderBitrate => "VIDEO_TARGET_ENCODER_BITRATE",
                Self::VideoBucketDelayMs => "VIDEO_BUCKET_DELAY_MS",
                Self::StunRttMs => "STUN_RTT_MS",
                Self::SocketDiscardedPps => "SOCKET_DISCARDED_PPS",
                Self::RtcMicJitterMs => "RTC_MIC_JITTER_MS",
                Self::RtcMicPps => "RTC_MIC_PPS",
                Self::RtcMicFractionPacketLostPercent => {
                    "RTC_MIC_FRACTION_PACKET_LOST_PERCENT"
                }
                Self::RtcMicBitrate => "RTC_MIC_BITRATE",
                Self::RtcMicRttMs => "RTC_MIC_RTT_MS",
                Self::RtcSpkPps => "RTC_SPK_PPS",
                Self::RtcSpkFractionPacketLostPercent => {
                    "RTC_SPK_FRACTION_PACKET_LOST_PERCENT"
                }
                Self::RtcSpkJitterMs => "RTC_SPK_JITTER_MS",
                Self::RtcSpkFractionDecoderLossPercent => {
                    "RTC_SPK_FRACTION_DECODER_LOSS_PERCENT"
                }
                Self::RtcSpkBitrate => "RTC_SPK_BITRATE",
                Self::RtcSpkCurrentDelayMs => "RTC_SPK_CURRENT_DELAY_MS",
                Self::RtcSpkJitterBufferMs => "RTC_SPK_JITTER_BUFFER_MS",
                Self::VideoSentRttMs => "VIDEO_SENT_RTT_MS",
                Self::VideoEncodeUsagePercent => "VIDEO_ENCODE_USAGE_PERCENT",
                Self::VideoNacksReceived => "VIDEO_NACKS_RECEIVED",
                Self::VideoPlisReceived => "VIDEO_PLIS_RECEIVED",
                Self::VideoEncodeMs => "VIDEO_ENCODE_MS",
                Self::VideoInputFps => "VIDEO_INPUT_FPS",
                Self::VideoEncodeFps => "VIDEO_ENCODE_FPS",
                Self::VideoSentFps => "VIDEO_SENT_FPS",
                Self::VideoFirsReceived => "VIDEO_FIRS_RECEIVED",
                Self::VideoSentPps => "VIDEO_SENT_PPS",
                Self::VideoSentFractionPacketLostPercent => {
                    "VIDEO_SENT_FRACTION_PACKET_LOST_PERCENT"
                }
                Self::VideoSentBitrate => "VIDEO_SENT_BITRATE",
                Self::VideoDroppedFps => "VIDEO_DROPPED_FPS",
                Self::VideoTargetDelayMs => "VIDEO_TARGET_DELAY_MS",
                Self::VideoDecodeMs => "VIDEO_DECODE_MS",
                Self::VideoOutputFps => "VIDEO_OUTPUT_FPS",
                Self::VideoReceivedPps => "VIDEO_RECEIVED_PPS",
                Self::VideoReceivedFractionPacketLostPercent => {
                    "VIDEO_RECEIVED_FRACTION_PACKET_LOST_PERCENT"
                }
                Self::VideoRenderDelayMs => "VIDEO_RENDER_DELAY_MS",
                Self::VideoReceivedFps => "VIDEO_RECEIVED_FPS",
                Self::VideoDecodeFps => "VIDEO_DECODE_FPS",
                Self::VideoNacksSent => "VIDEO_NACKS_SENT",
                Self::VideoFirsSent => "VIDEO_FIRS_SENT",
                Self::VideoReceivedBitrate => "VIDEO_RECEIVED_BITRATE",
                Self::VideoCurrentDelayMs => "VIDEO_CURRENT_DELAY_MS",
                Self::VideoJitterBufferMs => "VIDEO_JITTER_BUFFER_MS",
                Self::VideoDiscardedPps => "VIDEO_DISCARDED_PPS",
                Self::VideoPlisSent => "VIDEO_PLIS_SENT",
                Self::VideoReceivedJitterMs => "VIDEO_RECEIVED_JITTER_MS",
                Self::VideoLocalRenderFps => "VIDEO_LOCAL_RENDER_FPS",
                Self::VideoRemoteRenderFps => "VIDEO_REMOTE_RENDER_FPS",
                Self::VideoInputHeight => "VIDEO_INPUT_HEIGHT",
                Self::VideoEncodeHeight => "VIDEO_ENCODE_HEIGHT",
                Self::VideoSentQpSum => "VIDEO_SENT_QP_SUM",
                Self::VideoDecodeHeight => "VIDEO_DECODE_HEIGHT",
                Self::VideoReceivedQpSum => "VIDEO_RECEIVED_QP_SUM",
                Self::VideoEncodeWidth => "VIDEO_ENCODE_WIDTH",
                Self::VideoDecodeWidth => "VIDEO_DECODE_WIDTH",
                Self::VideoEncoderIsHardware => "VIDEO_ENCODER_IS_HARDWARE",
                Self::VideoDecoderIsHardware => "VIDEO_DECODER_IS_HARDWARE",
                Self::VideoFreezeCount => "VIDEO_FREEZE_COUNT",
                Self::VideoFreezeDuration => "VIDEO_FREEZE_DURATION",
                Self::VideoPauseCount => "VIDEO_PAUSE_COUNT",
                Self::VideoPauseDuration => "VIDEO_PAUSE_DURATION",
                Self::VideoQualityReason => "VIDEO_QUALITY_REASON",
                Self::VideoProcessingTime => "VIDEO_PROCESSING_TIME",
                Self::RtcSpkAudioLevel => "RTC_SPK_AUDIO_LEVEL",
                Self::RtcMicAudioLevel => "RTC_MIC_AUDIO_LEVEL",
                Self::RtcSpkTotalLost => "RTC_SPK_TOTAL_LOST",
                Self::RtcSpkTotalExpected => "RTC_SPK_TOTAL_EXPECTED",
                Self::RtcSpkTotalRecoveredRed => "RTC_SPK_TOTAL_RECOVERED_RED",
                Self::RtcSpkTotalRecoveredFec => "RTC_SPK_TOTAL_RECOVERED_FEC",
                Self::VideoQualityLimitationDurationCpu => {
                    "VIDEO_QUALITY_LIMITATION_DURATION_CPU"
                }
                Self::VideoCodecDegradationHighEncodeCpu => {
                    "VIDEO_CODEC_DEGRADATION_HIGH_ENCODE_CPU"
                }
                Self::VideoCodecDegradationEncodeFailure => {
                    "VIDEO_CODEC_DEGRADATION_ENCODE_FAILURE"
                }
                Self::VideoRenderHeight => "VIDEO_RENDER_HEIGHT",
                Self::VideoRenderWidth => "VIDEO_RENDER_WIDTH",
                Self::VideoInputWidth => "VIDEO_INPUT_WIDTH",
                Self::VideoSentJitterMs => "VIDEO_SENT_JITTER_MS",
                Self::AudioSentTransformPps => "AUDIO_SENT_TRANSFORM_PPS",
                Self::AudioReceivedTransformPps => "AUDIO_RECEIVED_TRANSFORM_PPS",
                Self::VideoSentTransformPps => "VIDEO_SENT_TRANSFORM_PPS",
                Self::VideoReceivedTransformPps => "VIDEO_RECEIVED_TRANSFORM_PPS",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "VIDEO_ACTUAL_ENCODER_BITRATE" => Some(Self::VideoActualEncoderBitrate),
                "VIDEO_AVAILABLE_SEND_BANDWIDTH" => {
                    Some(Self::VideoAvailableSendBandwidth)
                }
                "VIDEO_RETRANSMIT_BITRATE" => Some(Self::VideoRetransmitBitrate),
                "VIDEO_AVAILABLE_RECEIVE_BANDWIDTH" => {
                    Some(Self::VideoAvailableReceiveBandwidth)
                }
                "VIDEO_TARGET_ENCODER_BITRATE" => Some(Self::VideoTargetEncoderBitrate),
                "VIDEO_BUCKET_DELAY_MS" => Some(Self::VideoBucketDelayMs),
                "STUN_RTT_MS" => Some(Self::StunRttMs),
                "SOCKET_DISCARDED_PPS" => Some(Self::SocketDiscardedPps),
                "RTC_MIC_JITTER_MS" => Some(Self::RtcMicJitterMs),
                "RTC_MIC_PPS" => Some(Self::RtcMicPps),
                "RTC_MIC_FRACTION_PACKET_LOST_PERCENT" => {
                    Some(Self::RtcMicFractionPacketLostPercent)
                }
                "RTC_MIC_BITRATE" => Some(Self::RtcMicBitrate),
                "RTC_MIC_RTT_MS" => Some(Self::RtcMicRttMs),
                "RTC_SPK_PPS" => Some(Self::RtcSpkPps),
                "RTC_SPK_FRACTION_PACKET_LOST_PERCENT" => {
                    Some(Self::RtcSpkFractionPacketLostPercent)
                }
                "RTC_SPK_JITTER_MS" => Some(Self::RtcSpkJitterMs),
                "RTC_SPK_FRACTION_DECODER_LOSS_PERCENT" => {
                    Some(Self::RtcSpkFractionDecoderLossPercent)
                }
                "RTC_SPK_BITRATE" => Some(Self::RtcSpkBitrate),
                "RTC_SPK_CURRENT_DELAY_MS" => Some(Self::RtcSpkCurrentDelayMs),
                "RTC_SPK_JITTER_BUFFER_MS" => Some(Self::RtcSpkJitterBufferMs),
                "VIDEO_SENT_RTT_MS" => Some(Self::VideoSentRttMs),
                "VIDEO_ENCODE_USAGE_PERCENT" => Some(Self::VideoEncodeUsagePercent),
                "VIDEO_NACKS_RECEIVED" => Some(Self::VideoNacksReceived),
                "VIDEO_PLIS_RECEIVED" => Some(Self::VideoPlisReceived),
                "VIDEO_ENCODE_MS" => Some(Self::VideoEncodeMs),
                "VIDEO_INPUT_FPS" => Some(Self::VideoInputFps),
                "VIDEO_ENCODE_FPS" => Some(Self::VideoEncodeFps),
                "VIDEO_SENT_FPS" => Some(Self::VideoSentFps),
                "VIDEO_FIRS_RECEIVED" => Some(Self::VideoFirsReceived),
                "VIDEO_SENT_PPS" => Some(Self::VideoSentPps),
                "VIDEO_SENT_FRACTION_PACKET_LOST_PERCENT" => {
                    Some(Self::VideoSentFractionPacketLostPercent)
                }
                "VIDEO_SENT_BITRATE" => Some(Self::VideoSentBitrate),
                "VIDEO_DROPPED_FPS" => Some(Self::VideoDroppedFps),
                "VIDEO_TARGET_DELAY_MS" => Some(Self::VideoTargetDelayMs),
                "VIDEO_DECODE_MS" => Some(Self::VideoDecodeMs),
                "VIDEO_OUTPUT_FPS" => Some(Self::VideoOutputFps),
                "VIDEO_RECEIVED_PPS" => Some(Self::VideoReceivedPps),
                "VIDEO_RECEIVED_FRACTION_PACKET_LOST_PERCENT" => {
                    Some(Self::VideoReceivedFractionPacketLostPercent)
                }
                "VIDEO_RENDER_DELAY_MS" => Some(Self::VideoRenderDelayMs),
                "VIDEO_RECEIVED_FPS" => Some(Self::VideoReceivedFps),
                "VIDEO_DECODE_FPS" => Some(Self::VideoDecodeFps),
                "VIDEO_NACKS_SENT" => Some(Self::VideoNacksSent),
                "VIDEO_FIRS_SENT" => Some(Self::VideoFirsSent),
                "VIDEO_RECEIVED_BITRATE" => Some(Self::VideoReceivedBitrate),
                "VIDEO_CURRENT_DELAY_MS" => Some(Self::VideoCurrentDelayMs),
                "VIDEO_JITTER_BUFFER_MS" => Some(Self::VideoJitterBufferMs),
                "VIDEO_DISCARDED_PPS" => Some(Self::VideoDiscardedPps),
                "VIDEO_PLIS_SENT" => Some(Self::VideoPlisSent),
                "VIDEO_RECEIVED_JITTER_MS" => Some(Self::VideoReceivedJitterMs),
                "VIDEO_LOCAL_RENDER_FPS" => Some(Self::VideoLocalRenderFps),
                "VIDEO_REMOTE_RENDER_FPS" => Some(Self::VideoRemoteRenderFps),
                "VIDEO_INPUT_HEIGHT" => Some(Self::VideoInputHeight),
                "VIDEO_ENCODE_HEIGHT" => Some(Self::VideoEncodeHeight),
                "VIDEO_SENT_QP_SUM" => Some(Self::VideoSentQpSum),
                "VIDEO_DECODE_HEIGHT" => Some(Self::VideoDecodeHeight),
                "VIDEO_RECEIVED_QP_SUM" => Some(Self::VideoReceivedQpSum),
                "VIDEO_ENCODE_WIDTH" => Some(Self::VideoEncodeWidth),
                "VIDEO_DECODE_WIDTH" => Some(Self::VideoDecodeWidth),
                "VIDEO_ENCODER_IS_HARDWARE" => Some(Self::VideoEncoderIsHardware),
                "VIDEO_DECODER_IS_HARDWARE" => Some(Self::VideoDecoderIsHardware),
                "VIDEO_FREEZE_COUNT" => Some(Self::VideoFreezeCount),
                "VIDEO_FREEZE_DURATION" => Some(Self::VideoFreezeDuration),
                "VIDEO_PAUSE_COUNT" => Some(Self::VideoPauseCount),
                "VIDEO_PAUSE_DURATION" => Some(Self::VideoPauseDuration),
                "VIDEO_QUALITY_REASON" => Some(Self::VideoQualityReason),
                "VIDEO_PROCESSING_TIME" => Some(Self::VideoProcessingTime),
                "RTC_SPK_AUDIO_LEVEL" => Some(Self::RtcSpkAudioLevel),
                "RTC_MIC_AUDIO_LEVEL" => Some(Self::RtcMicAudioLevel),
                "RTC_SPK_TOTAL_LOST" => Some(Self::RtcSpkTotalLost),
                "RTC_SPK_TOTAL_EXPECTED" => Some(Self::RtcSpkTotalExpected),
                "RTC_SPK_TOTAL_RECOVERED_RED" => Some(Self::RtcSpkTotalRecoveredRed),
                "RTC_SPK_TOTAL_RECOVERED_FEC" => Some(Self::RtcSpkTotalRecoveredFec),
                "VIDEO_QUALITY_LIMITATION_DURATION_CPU" => {
                    Some(Self::VideoQualityLimitationDurationCpu)
                }
                "VIDEO_CODEC_DEGRADATION_HIGH_ENCODE_CPU" => {
                    Some(Self::VideoCodecDegradationHighEncodeCpu)
                }
                "VIDEO_CODEC_DEGRADATION_ENCODE_FAILURE" => {
                    Some(Self::VideoCodecDegradationEncodeFailure)
                }
                "VIDEO_RENDER_HEIGHT" => Some(Self::VideoRenderHeight),
                "VIDEO_RENDER_WIDTH" => Some(Self::VideoRenderWidth),
                "VIDEO_INPUT_WIDTH" => Some(Self::VideoInputWidth),
                "VIDEO_SENT_JITTER_MS" => Some(Self::VideoSentJitterMs),
                "AUDIO_SENT_TRANSFORM_PPS" => Some(Self::AudioSentTransformPps),
                "AUDIO_RECEIVED_TRANSFORM_PPS" => Some(Self::AudioReceivedTransformPps),
                "VIDEO_SENT_TRANSFORM_PPS" => Some(Self::VideoSentTransformPps),
                "VIDEO_RECEIVED_TRANSFORM_PPS" => Some(Self::VideoReceivedTransformPps),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkStreamMetricFrame {
    #[prost(uint32, optional, tag = "3")]
    pub stream_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "4")]
    pub group_id: ::core::option::Option<u32>,
    #[prost(message, repeated, tag = "5")]
    pub metrics: ::prost::alloc::vec::Vec<SdkMetric>,
    #[prost(message, repeated, tag = "6")]
    pub dimensions: ::prost::alloc::vec::Vec<SdkStreamDimension>,
    #[prost(enumeration = "SdkStreamMediaType", optional, tag = "7")]
    pub media_type: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkClientMetricFrame {
    #[prost(message, repeated, tag = "1")]
    pub global_metrics: ::prost::alloc::vec::Vec<SdkMetric>,
    #[prost(message, repeated, tag = "2")]
    pub stream_metric_frames: ::prost::alloc::vec::Vec<SdkStreamMetricFrame>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkStreamDimension {
    #[prost(enumeration = "sdk_stream_dimension::Type", optional, tag = "1")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<SdkDimensionValue>,
}
/// Nested message and enum types in `SdkStreamDimension`.
pub mod sdk_stream_dimension {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        VideoEncoderName = 1,
        VideoDecoderName = 2,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::VideoEncoderName => "VIDEO_ENCODER_NAME",
                Self::VideoDecoderName => "VIDEO_DECODER_NAME",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "VIDEO_ENCODER_NAME" => Some(Self::VideoEncoderName),
                "VIDEO_DECODER_NAME" => Some(Self::VideoDecoderName),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkDimensionValue {
    #[prost(string, optional, tag = "1")]
    pub string_value: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "2")]
    pub bool_value: ::core::option::Option<bool>,
    #[prost(uint64, optional, tag = "3")]
    pub uint_value: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkDataMessageFrame {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<SdkDataMessagePayload>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkDataMessagePayload {
    #[prost(string, optional, tag = "1")]
    pub topic: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub data: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, optional, tag = "3")]
    pub lifetime_ms: ::core::option::Option<u32>,
    #[prost(string, optional, tag = "4")]
    pub sender_attendee_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "5")]
    pub ingest_time_ns: ::core::option::Option<i64>,
    #[prost(string, optional, tag = "6")]
    pub sender_external_user_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
#[prost(skip_debug)]
pub struct SdkTurnCredentials {
    #[prost(string, optional, tag = "1")]
    pub username: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub password: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "3")]
    pub ttl: ::core::option::Option<u32>,
    #[prost(string, repeated, tag = "4")]
    pub uris: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkTranscriptItem {
    #[prost(string, optional, tag = "1")]
    pub content: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "2")]
    pub end_time: ::core::option::Option<i64>,
    #[prost(string, optional, tag = "3")]
    pub speaker_attendee_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub speaker_external_user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "5")]
    pub start_time: ::core::option::Option<i64>,
    #[prost(enumeration = "sdk_transcript_item::Type", optional, tag = "6")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(bool, optional, tag = "7")]
    pub vocabulary_filter_match: ::core::option::Option<bool>,
    #[prost(double, optional, tag = "8")]
    pub confidence: ::core::option::Option<f64>,
    #[prost(bool, optional, tag = "9")]
    pub stable: ::core::option::Option<bool>,
}
/// Nested message and enum types in `SdkTranscriptItem`.
pub mod sdk_transcript_item {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        Pronunciation = 1,
        Punctuation = 2,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Pronunciation => "PRONUNCIATION",
                Self::Punctuation => "PUNCTUATION",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "PRONUNCIATION" => Some(Self::Pronunciation),
                "PUNCTUATION" => Some(Self::Punctuation),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkTranscriptEntity {
    #[prost(string, optional, tag = "1")]
    pub category: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(double, optional, tag = "2")]
    pub confidence: ::core::option::Option<f64>,
    #[prost(string, optional, tag = "3")]
    pub content: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "4")]
    pub end_time: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "5")]
    pub start_time: ::core::option::Option<i64>,
    #[prost(string, optional, tag = "6")]
    pub r#type: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkTranscriptAlternative {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<SdkTranscriptItem>,
    #[prost(string, optional, tag = "2")]
    pub transcript: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "3")]
    pub entities: ::prost::alloc::vec::Vec<SdkTranscriptEntity>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkTranscriptLanguageWithScore {
    #[prost(string, optional, tag = "1")]
    pub language_code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(double, optional, tag = "2")]
    pub score: ::core::option::Option<f64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkTranscriptResult {
    #[prost(message, repeated, tag = "1")]
    pub alternatives: ::prost::alloc::vec::Vec<SdkTranscriptAlternative>,
    #[prost(string, optional, tag = "2")]
    pub channel_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "3")]
    pub end_time: ::core::option::Option<i64>,
    #[prost(bool, optional, tag = "4")]
    pub is_partial: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "5")]
    pub result_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "6")]
    pub start_time: ::core::option::Option<i64>,
    #[prost(string, optional, tag = "7")]
    pub language_code: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "8")]
    pub language_identification: ::prost::alloc::vec::Vec<
        SdkTranscriptLanguageWithScore,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkTranscript {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<SdkTranscriptResult>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkTranscriptionStatus {
    #[prost(enumeration = "sdk_transcription_status::Type", optional, tag = "1")]
    pub r#type: ::core::option::Option<i32>,
    #[prost(int64, optional, tag = "2")]
    pub event_time: ::core::option::Option<i64>,
    #[prost(string, optional, tag = "3")]
    pub transcription_region: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub transcription_configuration: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
    #[prost(string, optional, tag = "5")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `SdkTranscriptionStatus`.
pub mod sdk_transcription_status {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Type {
        Started = 1,
        Interrupted = 2,
        Resumed = 3,
        Stopped = 4,
        Failed = 5,
    }
    impl Type {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Started => "STARTED",
                Self::Interrupted => "INTERRUPTED",
                Self::Resumed => "RESUMED",
                Self::Stopped => "STOPPED",
                Self::Failed => "FAILED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "STARTED" => Some(Self::Started),
                "INTERRUPTED" => Some(Self::Interrupted),
                "RESUMED" => Some(Self::Resumed),
                "STOPPED" => Some(Self::Stopped),
                "FAILED" => Some(Self::Failed),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkTranscriptEvent {
    #[prost(oneof = "sdk_transcript_event::Event", tags = "1, 2")]
    pub event: ::core::option::Option<sdk_transcript_event::Event>,
}
/// Nested message and enum types in `SdkTranscriptEvent`.
pub mod sdk_transcript_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        Status(super::SdkTranscriptionStatus),
        #[prost(message, tag = "2")]
        Transcript(super::SdkTranscript),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkTranscriptFrame {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<SdkTranscriptEvent>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkRemoteVideoUpdateFrame {
    #[prost(message, repeated, tag = "1")]
    pub added_or_updated_video_subscriptions: ::prost::alloc::vec::Vec<
        SdkVideoSubscriptionConfiguration,
    >,
    #[prost(string, repeated, tag = "2")]
    pub removed_video_subscription_mids: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkVideoSubscriptionConfiguration {
    #[prost(string, required, tag = "1")]
    pub mid: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub attendee_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "3")]
    pub stream_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "4")]
    pub priority: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "5")]
    pub target_bitrate_kbps: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "6")]
    pub group_id: ::core::option::Option<u32>,
    #[prost(enumeration = "SdkVideoQualityAdaptationPreference", optional, tag = "7")]
    pub quality_adaptation_preference: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkNotificationFrame {
    #[prost(
        enumeration = "sdk_notification_frame::NotificationLevel",
        optional,
        tag = "1",
        default = "Error"
    )]
    pub level: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
}
/// Nested message and enum types in `SdkNotificationFrame`.
pub mod sdk_notification_frame {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum NotificationLevel {
        Info = 1,
        Warning = 2,
        Error = 3,
    }
    impl NotificationLevel {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Info => "INFO",
                Self::Warning => "WARNING",
                Self::Error => "ERROR",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "INFO" => Some(Self::Info),
                "WARNING" => Some(Self::Warning),
                "ERROR" => Some(Self::Error),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkPrimaryMeetingJoinFrame {
    #[prost(message, optional, tag = "1")]
    pub credentials: ::core::option::Option<SdkMeetingSessionCredentials>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkPrimaryMeetingJoinAckFrame {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkPrimaryMeetingLeaveFrame {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
#[prost(skip_debug)]
pub struct SdkMeetingSessionCredentials {
    #[prost(string, optional, tag = "1")]
    pub attendee_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub external_user_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub join_token: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdkMeetingSessionTimingFrame {
    #[prost(message, repeated, tag = "1")]
    pub signaling: ::prost::alloc::vec::Vec<SdkMeetingSessionSignalingTiming>,
    #[prost(message, repeated, tag = "2")]
    pub remote_audio: ::prost::alloc::vec::Vec<SdkMeetingSessionRemoteAudioTiming>,
    #[prost(message, repeated, tag = "3")]
    pub local_audio: ::prost::alloc::vec::Vec<SdkMeetingSessionLocalAudioTiming>,
    #[prost(message, repeated, tag = "4")]
    pub local_video: ::prost::alloc::vec::Vec<SdkMeetingSessionLocalVideoTiming>,
    #[prost(message, repeated, tag = "5")]
    pub remote_videos: ::prost::alloc::vec::Vec<SdkMeetingSessionRemoteVideoTiming>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkMeetingSessionSignalingTiming {
    #[prost(int64, optional, tag = "1")]
    pub start_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "2")]
    pub join_sent_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "3")]
    pub join_ack_received_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "4")]
    pub transport_connected_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "5")]
    pub create_offer_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "6")]
    pub set_local_description_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "7")]
    pub set_remote_description_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "8")]
    pub ice_gathering_start_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "9")]
    pub ice_gathering_complete_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "10")]
    pub ice_connected_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "11")]
    pub subscribe_sent_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "12")]
    pub subscribe_ack_ms: ::core::option::Option<i64>,
    #[prost(bool, optional, tag = "13")]
    pub timed_out: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkMeetingSessionRemoteAudioTiming {
    #[prost(int64, optional, tag = "1")]
    pub added_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "2")]
    pub first_packet_received_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "3")]
    pub first_frame_rendered_ms: ::core::option::Option<i64>,
    #[prost(bool, optional, tag = "4")]
    pub timed_out: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "5")]
    pub removed: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkMeetingSessionLocalAudioTiming {
    #[prost(int64, optional, tag = "1")]
    pub added_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "2")]
    pub first_frame_captured_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "3")]
    pub first_packet_sent_ms: ::core::option::Option<i64>,
    #[prost(bool, optional, tag = "4")]
    pub timed_out: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "5")]
    pub removed: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkMeetingSessionLocalVideoTiming {
    #[prost(int64, optional, tag = "1")]
    pub added_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "2")]
    pub first_frame_captured_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "3")]
    pub first_frame_sent_ms: ::core::option::Option<i64>,
    #[prost(bool, optional, tag = "4")]
    pub timed_out: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "5")]
    pub removed: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SdkMeetingSessionRemoteVideoTiming {
    #[prost(uint32, optional, tag = "1")]
    pub group_id: ::core::option::Option<u32>,
    #[prost(int64, optional, tag = "2")]
    pub added_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "3")]
    pub first_packet_received_ms: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "4")]
    pub first_frame_rendered_ms: ::core::option::Option<i64>,
    #[prost(bool, optional, tag = "5")]
    pub timed_out: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "6")]
    pub removed: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SdkJoinFlags {
    HasStreamUpdate = 2,
    CompleteVideoSourcesList = 16,
    ExcludeSelfContentInIndex = 32,
}
impl SdkJoinFlags {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::HasStreamUpdate => "HAS_STREAM_UPDATE",
            Self::CompleteVideoSourcesList => "COMPLETE_VIDEO_SOURCES_LIST",
            Self::ExcludeSelfContentInIndex => "EXCLUDE_SELF_CONTENT_IN_INDEX",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "HAS_STREAM_UPDATE" => Some(Self::HasStreamUpdate),
            "COMPLETE_VIDEO_SOURCES_LIST" => Some(Self::CompleteVideoSourcesList),
            "EXCLUDE_SELF_CONTENT_IN_INDEX" => Some(Self::ExcludeSelfContentInIndex),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SdkServerSideNetworkAdaption {
    Default = 1,
    None = 2,
    BandwidthProbing = 3,
    BandwidthProbingAndVideoQualityAdaption = 4,
}
impl SdkServerSideNetworkAdaption {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Default => "DEFAULT",
            Self::None => "NONE",
            Self::BandwidthProbing => "BANDWIDTH_PROBING",
            Self::BandwidthProbingAndVideoQualityAdaption => {
                "BANDWIDTH_PROBING_AND_VIDEO_QUALITY_ADAPTION"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEFAULT" => Some(Self::Default),
            "NONE" => Some(Self::None),
            "BANDWIDTH_PROBING" => Some(Self::BandwidthProbing),
            "BANDWIDTH_PROBING_AND_VIDEO_QUALITY_ADAPTION" => {
                Some(Self::BandwidthProbingAndVideoQualityAdaption)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SdkStreamServiceType {
    Rx = 1,
    Tx = 2,
    Duplex = 3,
}
impl SdkStreamServiceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Rx => "RX",
            Self::Tx => "TX",
            Self::Duplex => "DUPLEX",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RX" => Some(Self::Rx),
            "TX" => Some(Self::Tx),
            "DUPLEX" => Some(Self::Duplex),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SdkStreamMediaType {
    Audio = 1,
    Video = 2,
}
impl SdkStreamMediaType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Audio => "AUDIO",
            Self::Video => "VIDEO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUDIO" => Some(Self::Audio),
            "VIDEO" => Some(Self::Video),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SdkPingPongType {
    Ping = 1,
    Pong = 2,
}
impl SdkPingPongType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Ping => "PING",
            Self::Pong => "PONG",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PING" => Some(Self::Ping),
            "PONG" => Some(Self::Pong),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SdkVideoQualityAdaptationPreference {
    Balanced = 1,
    MaintainFramerate = 2,
    MaintainResolution = 3,
}
impl SdkVideoQualityAdaptationPreference {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Balanced => "BALANCED",
            Self::MaintainFramerate => "MAINTAIN_FRAMERATE",
            Self::MaintainResolution => "MAINTAIN_RESOLUTION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BALANCED" => Some(Self::Balanced),
            "MAINTAIN_FRAMERATE" => Some(Self::MaintainFramerate),
            "MAINTAIN_RESOLUTION" => Some(Self::MaintainResolution),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SdkVideoCodecCapability {
    Vp8 = 1,
    H264BaselineProfile = 2,
    H264ConstrainedBaselineProfile = 3,
    H264MainProfile = 4,
    H264HighProfile = 5,
    H264ConstrainedHighProfile = 6,
    Vp9Profile0 = 8,
    Av1MainProfile = 11,
}
impl SdkVideoCodecCapability {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Vp8 => "VP8",
            Self::H264BaselineProfile => "H264_BASELINE_PROFILE",
            Self::H264ConstrainedBaselineProfile => "H264_CONSTRAINED_BASELINE_PROFILE",
            Self::H264MainProfile => "H264_MAIN_PROFILE",
            Self::H264HighProfile => "H264_HIGH_PROFILE",
            Self::H264ConstrainedHighProfile => "H264_CONSTRAINED_HIGH_PROFILE",
            Self::Vp9Profile0 => "VP9_PROFILE_0",
            Self::Av1MainProfile => "AV1_MAIN_PROFILE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VP8" => Some(Self::Vp8),
            "H264_BASELINE_PROFILE" => Some(Self::H264BaselineProfile),
            "H264_CONSTRAINED_BASELINE_PROFILE" => {
                Some(Self::H264ConstrainedBaselineProfile)
            }
            "H264_MAIN_PROFILE" => Some(Self::H264MainProfile),
            "H264_HIGH_PROFILE" => Some(Self::H264HighProfile),
            "H264_CONSTRAINED_HIGH_PROFILE" => Some(Self::H264ConstrainedHighProfile),
            "VP9_PROFILE_0" => Some(Self::Vp9Profile0),
            "AV1_MAIN_PROFILE" => Some(Self::Av1MainProfile),
            _ => None,
        }
    }
}
